{% set name = "django-sortedm2m" %}
{% set version = "4.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/jazzband/django-sortedm2m.git
  git_rev: "{{ version }}"
  folder: build

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - django
  run:
    - python
    - django

test:
  imports:
    - sortedm2m

about:
  home: "https://github.com/jazzband/django-sortedm2m"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Drop-in replacement for Django's many to many field with sorted relations."
  doc_url: https://github.com/jazzband/django-sortedm2m
  dev_url: https://github.com/jazzband/django-sortedm2m

extra:
  recipe-maintainers:
    - https://github.com/gb119
